<a href="https://colab.research.google.com/github/m1deey/Late_delivery-/blob/main/Tables_matching.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
customers=pd.read_csv("olist_customers_dataset.csv")
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [ ]:
print(customers["customer_state"].unique())

['SP' 'SC' 'MG' 'PR' 'RJ' 'RS' 'PA' 'GO' 'ES' 'BA' 'MA' 'MS' 'CE' 'DF'
 'RN' 'PE' 'MT' 'AM' 'AP' 'AL' 'RO' 'PB' 'TO' 'PI' 'AC' 'SE' 'RR']

In [ ]:
print(customers["customer_city"].unique())

['franca' 'sao bernardo do campo' 'sao paulo' ... 'monte bonito'
 'sao rafael' 'eugenio de castro']

In [ ]:
customers.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [ ]:
items=pd.read_csv("olist_order_items_dataset.csv")
items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [ ]:
items.info()
items.isna().sum()
items.describe()
items.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [ ]:
payment=pd.read_csv("olist_order_payments_dataset.csv")
payment

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [ ]:
payment.isna().sum()
payment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [ ]:
review=pd.read_csv("olist_order_reviews_dataset.csv")
review

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53
...,...,...,...,...,...,...,...
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [ ]:
review.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [ ]:
order=pd.read_csv("olist_orders_dataset.csv")
order

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
59053,92fe9f93b7bb7a99f55be01fcd629140,c48354807076a9621832dc2144c3ce08,delivered,2018-06-04 16:08:03,2018-06-04 16:29:53,2018-06-07 13:53:00,2018-06-08 14:08:58,2018-06-28 00:00:00
59054,65d519114847599fa70eb2575fc38a15,1765628d55d5b0e3edbd16320eb576d7,delivered,2017-08-27 02:56:31,2017-08-28 03:04:11,2017-08-28 17:23:54,2017-08-31 19:42:43,2017-09-14 00:00:00
59055,51d1ab11845cf149f0b42a66dcea1ac1,aa48a7bcd1bdf28f822046696a7f4dfa,delivered,2018-02-25 20:45:09,2018-02-25 22:00:39,2018-02-27 17:43:06,2018-03-05 20:47:45,2018-03-16 00:00:00
59056,2dd1b3fcb05d15852bfc51a0a8405381,1b730e245b9e48cc3938dd8aa2dfebc4,delivered,2018-08-10 19:29:10,2018-08-10 19:44:31,2018-08-13 13:17:00,2018-08-18 14:17:33,2018-08-30 00:00:00
59057,c6007f8fb6a4e182373f412b2ee462bb,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
order['order_status'].value_counts()

order_status
delivered      57304
shipped          665
canceled         376
unavailable      348
processing       185
invoiced         173
created            5
approved           1
Name: count, dtype: int64

In [ ]:
order = order.drop(index=59057)

In [ ]:
order.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 101
order_delivered_carrier_date     1047
order_delivered_customer_date    1753
order_estimated_delivery_date       0
dtype: int64

In [ ]:
order[order['order_delivered_customer_date'].isna()]['order_status'].value_counts()

order_status
shipped        665
canceled       373
unavailable    348
processing     185
invoiced       173
created          5
delivered        3
approved         1
Name: count, dtype: int64

In [ ]:
order[order['order_delivered_carrier_date'].isna()]['order_status'].value_counts()

order_status
unavailable    348
canceled       335
processing     185
invoiced       173
created          5
approved         1
Name: count, dtype: int64

In [ ]:
date_cols = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for col in date_cols:
    order[col] = pd.to_datetime(order[col])

In [ ]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59057 entries, 0 to 59056
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       59057 non-null  object
 1   customer_id                    59057 non-null  object
 2   order_status                   59057 non-null  object
 3   order_purchase_timestamp       59057 non-null  datetime64[ns]
 4   order_approved_at              58956 non-null  datetime64[ns]
 5   order_delivered_carrier_date   58010 non-null  datetime64[ns]
 6   order_delivered_customer_date  57304 non-null  datetime64[ns]
 7   order_estimated_delivery_date  59057 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 3.6+ MB

In [ ]:
product=pd.read_csv("olist_products_dataset.csv")
product

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [86]:
product.isna().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [ ]:
product.dropna()
product.info()
print(product["product_category_name"].unique())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB
['perfumaria' 'artes' 'esporte_lazer' 'bebes' 'utilidades_domesticas'
 'instrumentos_musicais' 'cool_stuff' 'moveis_decoracao'
 'eletrodomesticos' 'brinquedos' 'cama_mesa_banho'
 'construcao_ferramentas_seguranca' 'informatica_acessorios'
 'beleza_saude' 'malas_acessorios' 'ferramentas_jardim'
 'moveis_escritorio' 'automotivo' 'eletronicos' 'fashion_calcados'
 'telefonia' 'papelaria' 'fashion_bolsas_e_acessorios' 'pcs'
 'casa_construcao' 'relogios_presentes'
 'construcao_ferramentas_construcao' 'pet_shop' 'eletroportateis'
 'agro_industria_e_comercio' nan 'moveis_sala' 'sinalizacao_e_seguranca'
 'climatizacao' 'consoles_games' 'livros_interesse_geral'
 'construcao_ferramentas_ferramentas' 'fashion_underwear_e_moda_praia'
 'fashion_roupa_masculina'
 'moveis_cozinha_area_de_servico_jantar_e_jardim'
 'industria_comercio_e_negocios' 'telefonia_fixa'
 'construcao_ferramentas_iluminacao' 'livros_tecnicos'
 'eletrodomesticos_2' 'artigos_de_festas' 'bebidas' 'market_place'
 'la_cuisine' 'construcao_ferramentas_jardim' 'fashion_roupa_feminina'
 'casa_conforto' 'audio' 'alimentos_bebidas' 'musica' 'alimentos'
 'tablets_impressao_imagem' 'livros_importados'
 'portateis_casa_forno_e_cafe' 'fashion_esporte' 'artigos_de_natal'
 'fashion_roupa_infanto_juvenil' 'dvds_blu_ray' 'artes_e_artesanato'
 'pc_gamer' 'moveis_quarto' 'cine_foto' 'fraldas_higiene' 'flores'
 'casa_conforto_2' 'portateis_cozinha_e_preparadores_de_alimentos'
 'seguros_e_servicos' 'moveis_colchao_e_estofado' 'cds_dvds_musicais']

In [ ]:
product[product['product_category_name'].isna()].head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0

In [ ]:
product['product_category_name'] = product['product_category_name'].fillna('unknown')
product['product_name_lenght'] = product['product_name_lenght'].fillna(0)
product['product_description_lenght'] = product['product_description_lenght'].fillna(0)
product['product_photos_qty'] = product['product_photos_qty'].fillna(0)
product.drop(
    product[
        product[['product_weight_g',
                 'product_length_cm',
                 'product_height_cm',
                 'product_width_cm']].isna().any(axis=1)
    ].index,
    inplace=True
)

In [ ]:
seller=pd.read_csv("olist_sellers_dataset.csv")
seller

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [ ]:
seller.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [ ]:
seller.duplicated().sum()

np.int64(0)

In [85]:
cat=pd.read_csv("product_category_name_translation.csv")
cat

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [105]:
import duckdb

con = duckdb.connect()
con.register("orders", order)
con.register("customers", customers)
con.register("items", items)
con.register("product", product)
con.register("payment", payment)
con.register("review", review)
con.register("seller", seller)

In [106]:
result = con.sql("""
SELECT
    o.order_id,
    o.customer_id,
    c.customer_unique_id,
    c.customer_city,
    c.customer_state
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id
LIMIT 10
""")

result

┌──────────────────────────────────┬──────────────────────────────────┬──────────────────────────────────┬──────────────────┬────────────────┐
│             order_id             │           customer_id            │        customer_unique_id        │  customer_city   │ customer_state │
│             varchar              │             varchar              │             varchar              │     varchar      │    varchar     │
├──────────────────────────────────┼──────────────────────────────────┼──────────────────────────────────┼──────────────────┼────────────────┤
│ b2059ed67ce144a36e2aa97d2c9e9ad2 │ 4e7b3e00288586ebd08712fdd0374a03 │ 060e732b5b29e8181a18229c7b0b2b5e │ sao paulo        │ SP             │
│ 951670f92359f4fe4a63112aa7306eba │ b2b6027bc5c5109e529d4dc6358b12c3 │ 259dac757896d24d7702b9acbbff3f3c │ mogi das cruzes  │ SP             │
│ 36e694cf4cbc2a4803200c35e84abdc4 │ fd826e7cf63160e536e0908c76c3f441 │ addec96d2e059c80c30fe6871d30d177 │ sao paulo        │ SP             │
│ 1ebeea841c590e86a14a0d7a48e7d062 │ 5adf08e34b2e993982a47070956c5c65 │ 1175e95fb47ddff9de6b2b06188f7e0d │ curitiba         │ PR             │
│ 7433cbcc783205509d66a5260da5b574 │ 4b7139f34592b3a31687243a302fa75b │ 9afe194fb833f79e300e37e580171f22 │ belo horizonte   │ MG             │
│ 8428e578bb1cf839ae26a6b7615502b9 │ 9fb35e4ed6f0a14a4977cd9aea4042bb │ 2a7745e1ed516b289ed9b29c7d0539a5 │ montes claros    │ MG             │
│ f86c5ed7048ac10eb88ec21c00f71892 │ 5aa9e4fdd4dfd20959cad2d772509598 │ 2a46fb94aef5cbeeb850418118cee090 │ rio de janeiro   │ RJ             │
│ 83d8f70418eefd96f37b483dff430305 │ b2d1536598b73a9abd18e0d75d92f0a3 │ 918dc87cd72cd9f6ed4bd442ed785235 │ lencois paulista │ SP             │
│ 852d2f4d37773bcbc21c8e09a05a4ea5 │ eabebad39a88bb6f5b52376faec28612 │ 295c05e81917928d76245e842748184d │ sao paulo        │ SP             │
│ 6c949e670b5d33dc8fb8ad25b6da4860 │ 1f1c7bf1c9b041b292af6c1c4470b753 │ 3151a81801c8386361b62277d7fa5ecf │ caxias do sul    │ RS             │
├──────────────────────────────────┴──────────────────────────────────┴──────────────────────────────────┴──────────────────┴────────────────┤
│ 10 rows                                                                                                                          5 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [110]:
result = con.sql("""
SELECT order_status , COUNT(order_id) as number_of_ordera
FROM orders
GROUP BY  order_status
""")

result

┌──────────────┬──────────────────┐
│ order_status │ number_of_ordera │
│   varchar    │      int64       │
├──────────────┼──────────────────┤
│ delivered    │            57304 │
│ invoiced     │              173 │
│ shipped      │              665 │
│ processing   │              185 │
│ unavailable  │              348 │
│ canceled     │              376 │
│ created      │                5 │
│ approved     │                1 │
└──────────────┴──────────────────┘

In [111]:
balance_check = con.sql("""
SELECT
    CASE WHEN order_delivered_customer_date > order_estimated_delivery_date
         THEN 1 ELSE 0 END AS is_late,
    COUNT(*) AS n_orders
FROM orders
WHERE order_status = 'delivered'
GROUP BY is_late
""")
balance_check

┌─────────┬──────────┐
│ is_late │ n_orders │
│  int32  │  int64   │
├─────────┼──────────┤
│       0 │    52706 │
│       1 │     4598 │
└─────────┴──────────┘

In [113]:
result = con.sql("""
SELECT
    o.order_id,
    c.customer_state,
    s.seller_state,
    cat.product_category_name_english AS product_category,
    p.product_weight_g,
    p.product_length_cm,
    p.product_height_cm,
    p.product_width_cm,
    EXTRACT(month FROM o.order_purchase_timestamp) AS purchase_month,
    EXTRACT(dow FROM o.order_purchase_timestamp) AS purchase_dow,
    COUNT(i.order_item_id) AS n_items,
    SUM(i.price) AS total_price,
    SUM(i.freight_value) AS total_freight,
    AVG(pay.payment_installments) AS avg_installments,
    CASE WHEN o.order_delivered_customer_date > o.order_estimated_delivery_date
         THEN 1 ELSE 0 END AS is_late
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN items i ON o.order_id = i.order_id
JOIN seller s ON i.seller_id = s.seller_id
JOIN product p ON i.product_id = p.product_id
LEFT JOIN cat ON p.product_category_name = cat.product_category_name
JOIN payment pay ON o.order_id = pay.order_id
WHERE o.order_status = 'delivered'
GROUP BY o.order_id, c.customer_state, s.seller_state, cat.product_category_name_english,
         p.product_weight_g, p.product_length_cm, p.product_height_cm, p.product_width_cm,
         o.order_purchase_timestamp, o.order_delivered_customer_date, o.order_estimated_delivery_date
""")
df = result.df()
df.head(10)

,order_id,customer_state,seller_state,product_category,product_weight_g,product_length_cm,product_height_cm,product_width_cm,purchase_month,purchase_dow,n_items,total_price,total_freight,avg_installments,is_late
0,36e694cf4cbc2a4803200c35e84abdc4,SP,SP,computers_accessories,100.0,16.0,3.0,13.0,2,1,1,14.99,7.78,1.0,0
1,7433cbcc783205509d66a5260da5b574,MG,PR,furniture_decor,2500.0,40.0,10.0,30.0,1,1,1,99.90,22.57,1.0,0
2,83d8f70418eefd96f37b483dff430305,SP,MG,air_conditioning,2000.0,20.0,10.0,20.0,9,6,1,99.00,18.31,1.0,0
3,6c949e670b5d33dc8fb8ad25b6da4860,RS,PR,health_beauty,433.0,19.0,14.0,15.0,4,0,1,84.00,18.47,10.0,0
4,17825f24877a9289214c301ae0c9424b,SP,SP,bed_bath_table,1383.0,50.0,10.0,40.0,5,4,2,179.80,24.26,1.0,1
5,830d8b3e6875ef6165ffc33219ab4fea,SC,RS,computers_accessories,2800.0,40.0,15.0,40.0,8,0,1,105.00,18.00,1.0,0
6,0198c71148c2e08c7c52b860f640fa4e,SP,SP,sports_leisure,1400.0,21.0,16.0,16.0,5,2,1,148.00,15.13,1.0,0
7,6cdc131d3c28253cd03cd0fbc3d5f938,SP,SP,bed_bath_table,950.0,45.0,15.0,35.0,5,3,1,69.90,10.21,2.0,0
8,d10eafa208521dc30796e6a26099b6a6,GO,SP,bed_bath_table,700.0,40.0,4.0,30.0,7,6,1,42.90,19.49,1.0,0
9,77b062be7c5bd21712905feb8e1cfeed,RJ,SP,bed_bath_table,1050.0,16.0,10.0,16.0,6,3,1,56.99,16.13,8.0,1

In [115]:
df.shape

(59254, 15)

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59254 entries, 0 to 59253
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           59254 non-null  object
 1   customer_state     59254 non-null  object
 2   seller_state       59254 non-null  object
 3   product_category   58420 non-null  object
 4   product_weight_g   59254 non-null  float64
 5   product_length_cm  59254 non-null  float64
 6   product_height_cm  59254 non-null  float64
 7   product_width_cm   59254 non-null  float64
 8   purchase_month     59254 non-null  int64
 9   purchase_dow       59254 non-null  int64
 10  n_items            59254 non-null  int64
 11  total_price        59254 non-null  float64
 12  total_freight      59254 non-null  float64
 13  avg_installments   59254 non-null  float64
 14  is_late            59254 non-null  int32
dtypes: float64(7), int32(1), int64(3), object(4)
memory usage: 6.6+ MB

In [121]:
df['product_category'] = df['product_category'].fillna('unknown')

In [122]:
df.isna().sum()

order_id             0
customer_state       0
seller_state         0
product_category     0
product_weight_g     0
product_length_cm    0
product_height_cm    0
product_width_cm     0
purchase_month       0
purchase_dow         0
n_items              0
total_price          0
total_freight        0
avg_installments     0
is_late              0
dtype: int64

In [123]:
df.shape
df['is_late'].value_counts(normalize=True)

is_late
0    0.921052
1    0.078948
Name: proportion, dtype: float64

In [124]:
df.to_csv('olist_late_delivery_dataset.csv', index=False)